ARG TF_PLUGIN_CACHE_DIR=/opt/terraform/plugin-cache

FROM quay.io/edge-infrastructure/assisted-service:latest AS service

FROM quay.io/assisted-installer-ops/base-python:3.11.0 as terraform

# RUN dnf -y install unzip
RUN curl --retry 5 -Lo terraform.zip https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip && \
     gunzip -S .zip -c terraform.zip > /usr/bin/terraform && \
     chmod +x /usr/bin/terraform && \
     rm -rf terraform.zip

WORKDIR /home/assisted-test-infra
COPY terraform_files .
ARG TF_PLUGIN_CACHE_DIR
RUN export TF_PLUGIN_CACHE_DIR && \
        mkdir -p "${TF_PLUGIN_CACHE_DIR}" && \
        for terraform_module in */; do terraform -chdir=${terraform_module} init; done

FROM quay.io/assisted-installer-ops/base-python:3.11.0

# A directory in the path with write permission even for non-root users
ENV TOOLS=/tools/
ENV PATH="$TOOLS:$PATH"
RUN mkdir $TOOLS --mode g+xw

# CRB repo is required for libvirt-devel
RUN dnf -y install --enablerepo=crb \
  make \
  gcc \
  unzip \
  curl-minimal \
  git \
  httpd-tools \
  jq \
  nss_wrapper \
  libvirt-client \
  guestfs-tools \
  libvirt-devel \
  libguestfs-tools \
  libxslt \
  xorriso \
   && dnf clean all

RUN curl --retry 5 -Lo packer.zip https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_386.zip && unzip packer.zip -d /usr/bin/ && mv /usr/bin/packer /usr/bin/packer.io && rm -rf packer.zip
RUN curl --retry 5 -L https://github.com/containers/podman/releases/download/v3.4.4/podman-remote-static.tar.gz -o "/tmp/podman-remote3.tar.gz" && \
    tar -zxvf /tmp/podman-remote3.tar.gz && \
    mv podman-remote-static /tools/podman-remote3 && \
    rm -f /tmp/podman-remote3.tar.gz &&\
    curl --retry 5 -L https://github.com/containers/podman/releases/download/v4.1.1/podman-remote-static.tar.gz -o "/tmp/podman-remote4.tar.gz" && \
    tar -zxvf /tmp/podman-remote4.tar.gz && \
    mv podman-remote-static /tools/podman-remote4 && \
    rm -f /tmp/podman-remote4.tar.gz

COPY --from=quay.io/ocp-splat/govc:v0.29.0 /govc /usr/local/bin

ARG TF_PLUGIN_CACHE_DIR
ENV TF_PLUGIN_CACHE_DIR=${TF_PLUGIN_CACHE_DIR}
COPY --from=terraform /usr/bin/terraform /usr/bin/terraform
COPY --from=terraform ${TF_PLUGIN_CACHE_DIR} ${TF_PLUGIN_CACHE_DIR}

WORKDIR /home/assisted-test-infra

COPY requirements.txt requirements-dev.txt ./
COPY --from=service /clients/assisted-service-client-*.tar.gz /build/pip/
RUN pip3 install --upgrade pip && \
      pip3 install --no-cache-dir -I -r ./requirements.txt -r ./requirements-dev.txt && \
      pip3 install --upgrade /build/pip/*

RUN curl --retry 5 -s https://storage.googleapis.com/golang/go1.18.1.linux-amd64.tar.gz | tar -C /usr/local -xz
ENV GOPATH=/go
ENV GOCACHE=/go/.cache
ENV PATH=$PATH:/usr/local/go/bin:/go/bin

COPY . .

RUN chgrp -R 0 /home/assisted-test-infra && \
    chmod -R g=u /home/assisted-test-infra

# setting pre-commit env
ENV PRE_COMMIT_HOME build
