- name: Create file custom manifests directories
  ansible.builtin.file:
    path: "{{ custom_manifests_dir }}/manifests"
    state: directory
    mode: '0755'

- name: Render custom manifests on disk
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ custom_manifests_dir }}/manifests/{{ item }}"
    mode: '0644'
  loop: "{{ oci_manifests }}"
