- name: Check if primary group exists and contains exactly 1 host
  ansible.builtin.fail:
    msg: Group primary must exits and contain exactly 1 host
  when: groups[primary_device_group_name] is not defined or (groups[primary_device_group_name] | length != 1)

- name: "Export connection details of primary device"
  ansible.builtin.template:
    src: "ci-machine-config.sh.j2"
    dest: "{{ shared_dir }}/ci-machine-config.sh"
    mode: 0644
  when: shared_dir is defined
