- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: /tmp/{{ ssh_private_key_name }}
  delegate_to: localhost
  register: ssh_key_pair
  run_once: true

- name: Set ssh settings as fact
  ansible.builtin.set_fact:
    ssh_private_key_path: "{{ ansible_user_dir }}/.ssh/{{ ssh_private_key_name }}"
    ssh_user: "{{ ansible_user_id }}"

- name: Copy private key to remote host
  ansible.builtin.copy:
    src: "{{ ssh_key_pair.filename }}"
    dest: "{{ ssh_private_key_path }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0600'

- name: Authorize key
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ ssh_key_pair.public_key }}"

- name: Generate SSH client configuration
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0600'
