- name: Destroy OCI infrastructure
  hosts: localhost
  vars_prompt:
    - name: oci_tf_state_file
      prompt: Terrafom state file that was used to create the infrastructure
      private: false
    - name: oci_tf_vars_file
      prompt: Place where the Terrafom variable file will be stored
      private: false
  vars:
    oci_terraform_workdir: "{{ [playbook_dir, '..', 'terraform_files', 'oci-ci-machine'] | path_join | realpath }}"
  roles:
    - name: oci/destroy_infra
