- name: "Restore Terraform state file from {{ equinix_tf_state_file }}"
  ansible.builtin.copy:
    src: "{{ equinix_tf_state_file }}"
    dest: "{{ terraform_equinix_workdir }}/terraform.tfstate"
    force: true
    mode: 0644

- name: "Destroy terraform infrastructure"
  community.general.terraform:
    project_path: "{{ terraform_equinix_workdir }}"
    state: absent
    force_init: false
    variables_files:
      - "{{ equinix_tf_vars_file }}"
    state_file: "{{ equinix_tf_state_file }}"
  register: destroyed_tf
  environment:
    METAL_AUTH_TOKEN: "{{ equinix_auth_token }}"
